.gitignore
README.md

Adds steps to set the development environment to the README,md file.

Adds details for local development to the README.md file

---

Makefile
README.md

Signed-off-by: Andres Gomez Coronel <andresgomezcoronel@gmail.com>

Adds contributing and Troubleshooting sections to the README.md file

---

src/pyspiffe/config.py
test/test_config.py

Closes #6 
Signed-off-by: Maximiliano Churichi <maximiliano.churichi@hpe.com>

Adds a base config setter

---

.gitignore
src/pyspiffe/config.py
test/test_config.py

Signed-off-by: Maximiliano Churichi <maximiliano.churichi@hpe.com>

More tests and docstrings improvements for the config setter class

---

.gitignore
src/pyspiffe/workloadapi/default_workload_api_client.py
src/pyspiffe/workloadapi/workload_api_client.py
test/workloadapi/test_default_workload_api_client.py

Initial stub of workload API client - Starts #13

Add initial workloadapi stub

---

CONTRIBUTING.md
README.md

Moved part of the README.md file into a new CONTRIBUTING.md file.
It also includes new conventions to follow when writing docstrings.

Adds CONTRIBUTING.md file and include details about docstring conventions

---

test/svid/x509svid/test_x509_svid.py

Fix failing test.

---

src/pyspiffe/bundle/jwt_bundle/jwt_bundle.py
src/pyspiffe/svid/jwt_svid.py
test/svid/jwtsvid/test_jwt_svid.py
test/svid/test_utils.py

- fixing the missing sub claim in token, adidng test for it, adding typing for test function

Fixes on jwt_svid parse and validate.

---

src/pyspiffe/bundle/jwt_bundle/exceptions.py
src/pyspiffe/bundle/jwt_bundle/jwt_bundle.py
src/pyspiffe/bundle/jwt_bundle/jwt_bundle_set.py
src/pyspiffe/bundle/x509_bundle/x509_bundle.py
src/pyspiffe/bundle/x509_bundle/x509_bundle_set.py
src/pyspiffe/svid/jwt_svid.py
test/bundle/jwt_bundle/test_jwt_bundle.py
test/bundle/jwt_bundle/test_jwt_bundle_set.py
test/svid/jwtsvid/test_jwt_svid.py

Adds an initial implementation of JWTBundleSet
Makes JwtBundle operation thread-safe
Fixes some typos and a variable name.

Intial Implementation of JWTBundleSet

---

src/pyspiffe/svid/jwt_svid.py
src/pyspiffe/svid/jwt_svid_validator.py
src/pyspiffe/workloadapi/default_workload_api_client.py
src/pyspiffe/workloadapi/exceptions.py
src/pyspiffe/workloadapi/workload_api_client.py
test/svid/test_utils.py
test/workloadapi/test_default_workload_api_client.py
test/workloadapi/test_default_workload_api_client_jwt.py

- created a new file for jwt related methods tests
- added implementation for fetch_jwt_svid method
- added tests for fetch_jwt_svid
- created FetchJwtSvidError exception
This partially addresses #62.

Fetch JWT SVID workload API implementation

---

test/svid/jwtsvid/test_jwt_svid.py
test/svid/test_utils.py

- removed duplicated code
- use create_jwt function where applicable
this addresses #74

Improving test_jwt_svid.py readability

---

src/pyspiffe/svid/exceptions.py
src/pyspiffe/svid/jwt_svid.py
src/pyspiffe/svid/jwt_svid_validator.py
src/pyspiffe/svid/x509_svid.py
test/bundle/x509bundle/test_x509_bundle.py
test/spiffe_id/test_spiffe_id.py
test/spiffe_id/test_trust_domain.py
test/svid/jwtsvid/test_jwt_svid.py
test/svid/jwtsvid/test_jwt_svid_validator.py
test/svid/x509svid/test_x509_svid.py
test/test_config.py
test/utils/test_certificate_utils.py

This PRs:
- Improves test coverage.
- Adds MissingClaimError to make clear difference between an invalid claim value and a missing required claim.
- Fixes some typos.

Improves test coverage

---

README.md

Add clarification about the status of library.

Add status of the library to README.

---

.github/workflows/pr_build.yaml

Install all required dependencies.
Add `workflow_dispatch` for triggering manually.

Fix workflow PR_Build

---

spiffe-tls/README.md
spiffe/README.md

This PR updates the README for the `spiffe` module, offering a clearer overview and more clear usage examples. 

docs: Update README with usage examples and module overviews

---

spiffe/src/spiffe/svid/errors.py

Minor changes in error messages.

Minor Amendments In Error Messages

---

spiffe-tls/poetry.lock
spiffe/poetry.lock
spiffe/src/spiffe/workloadapi/jwt_source.py
spiffe/src/spiffe/workloadapi/x509_source.py
spiffe/tests/workloadapi/test_jwt_source.py
spiffe/tests/workloadapi/test_x509_source.py

Enhance Mechanism of Notifying Subscribers In X.509 and JWT sources to make it more resilient in case a callback raise an exception.
Add tests for source subcribesr  methods.

Enhance Mechanism of Notifying Subscribers In X.509 and JWT sources. 

---

spiffe-tls/poetry.lock
spiffe-tls/pyproject.toml
spiffe/poetry.lock
spiffe/pyproject.toml

Remove Unused Dependencies And Improve Versions Selection

---

spiffe-tls/poetry.lock
spiffe-tls/pyproject.toml
spiffe-tls/tests/integration/test_listen_and_dial.py
spiffe/tests/integration/test_jwt_source.py
spiffe/tests/integration/test_x509_source.py

Set dev dependency version

---

.github/workflows/publish.yaml

Fix publish

---

spiffe-tls/poetry.lock
spiffe-tls/pyproject.toml

Pin `spiffe` Dependency in `spiffe-tls` Module

---

README.md
spiffe-tls/README.md
spiffe/README.md

Add Details to READMEs

---

README.md
spiffe-tls/README.md
spiffe/README.md

Add PyPI Bagdes. Amend Terminology

---

spiffe/pyproject.toml

Bump 'spiffe' version to 0.1.1

---

spiffe-tls/pyproject.toml
spiffe/pyproject.toml

Add GitHub Repository URL to pyproject.toml Metadata

---

.github/workflows/build.yaml

Ignore Changes In READMEs In Build Workflow

---

README.md
spiffe-tls/README.md
spiffe/README.md

Improve READMEs

---

spiffe-tls/poetry.lock
spiffe-tls/pyproject.toml

Bump spiffe-tls to 0.1.3

---

spiffe-tls/poetry.lock
spiffe-tls/pyproject.toml

Bump spiffe-tls to 0.1.4

---

spiffe/src/spiffe/spiffe_id/spiffe_id.py
spiffe/tests/unit/spiffe_id/test_spiffe_id.py

- Exposes the `path` on the `SpiffeId` as a property
- Resolves #275

Add path as property in SpiffeId

---

spiffe/pyproject.toml
spiffe/src/spiffe/spiffe_id/spiffe_id.py

Bump spiffe to 0.1.5

---

spiffe-tls/poetry.lock
spiffe-tls/pyproject.toml

Bump spiffe-tls to 0.1.5

---

spiffe/poetry.lock
spiffe/pyproject.toml
spiffe/tests/unit/svid/x509svid/test_x509_svid.py

feat: updates cryptography to v45.0.4
None
Updates cryptography to v45.0.4
fixes #298

feat: updates cryptography to v45.0.4
