HewlettPackard/py-spiffe

Pipfile
Pipfile.lock
setup.py
src/pyspiffe/spiffe_id/spiffe_id.py
src/pyspiffe/spiffe_id/trust_domain.py
test/spiffe_id/test_spiffe_id.py
test/spiffe_id/test_trust_domain.py

Implement the strong type `SpiffeId` following the SPIFFE standard.
Add some missing methods and validations to `TrustDomain` type.
Addresses #4

Implement `SpiffeId` type.

---

.travis.yml
tox.ini

Updates Travis-CI config at `.travis.yml` to run the test for the library on different versions of Python.
Changes:
- Set dist to `focal`. **Question:** Should we consider using an older one?
- Specifies the correct `tox` environment for each Python version
- Runs `tox` directly without calling `make test`
`make test` reminds for running the test locally at development.

Update Travis config to run the test

---

src/pyspiffe/config.py
test/test_config.py

- Adds the ability to set the socket endpoint programmatically
- Returns a Config object instead of a dict
Usage:
```python
config = ConfigSetter(spiffe_endpoint_socket='unix:///path/to/endpoint.sock')
config.spiffe_endpoint_socket
```
`ConfigSetter` first reads from the environment variable `SPIFFE_ENDPOINT_SOCKET`, if set, and then overrides the value with the parameter `spiffe_endpoint_socket`, if set. It raises a `ValueError` when neither of the values are set, or if it's set but is has an invalid socket path.

Config setter improvements

---

README.md
src/pyspiffe/bundle/jwt_bundle/jwt_bundle_set.py
src/pyspiffe/bundle/x509_bundle/x509_bundle_set.py
src/pyspiffe/svid/jwt_svid.py
src/pyspiffe/svid/x509_svid.py

This PR includes two simple changes:
- Removes old references to `src` directory on imports. 
- Adds the build badges from Travis to README.md file
I just want to have this changes in a different commit and not as part of a feature where they can be camouflaged.

Removes old references to src directory on imports. 

---

Makefile
src/pyspiffe/config.py
src/pyspiffe/spiffe_id/spiffe_id.py
src/pyspiffe/spiffe_id/trust_domain.py

`--ignore-missing-imports` option is used to avoid issues related to third party libraries missing type hints. In our code, this is the case for `rfc3987`. [Docs](https://mypy.readthedocs.io/en/stable/command_line.html#cmdoption-mypy-ignore-missing-imports)

Update mypy task to run against the src package.

---

Pipfile
Pipfile.lock

There is a new version of the cryptography library that includes a fix for a security issue: 
```
3.3.2 - 2021-02-07
SECURITY ISSUE: Fixed a bug where certain sequences of update() calls when symmetrically encrypting very 
large payloads (>2GB) could result in an integer overflow, leading to buffer overflows. CVE-2020-36242
```
[Source](https://github.com/pyca/cryptography/blob/master/CHANGELOG.rst#332---2021-02-07)

Updates cryptography version due to a Security Issue

---

src/pyspiffe/bundle/x509_bundle/x509_bundle.py
src/pyspiffe/svid/x509_svid.py
src/pyspiffe/utils/certificate_utils.py
src/pyspiffe/utils/exceptions.py
test/bundle/x509bundle/test_x509_bundle.py
test/svid/x509svid/test_x509_svid.py
test/utils/test_certificate_utils.py

There are several functions in `X509Svid` and `X509Bundle` that are duplicated, as both types were implemented in parallel. This PR refactors the common functionality and moves it to an utility module to handle certificates. Also took the opportunity to improve method and parameters names and error messages. 

Refactoring common functions used by X509Svid and X509Bundle

---

.circleci/config.yml
.gitignore
Makefile
README.md
pyproject.toml
tox.ini

This PR:
- Adds the test coverage of the project to the CI and post the results to [coveralls.io](https://coveralls.io/github/HewlettPackard/py-spiffe).
- Adds make task `test_cov` to generate test coverage and it won't try to post the results to the coveralls site.
- Adds `lint` to the CI. When running on the CI it will be executed using a `tox virtual environment` but when it is run locally it continues outside of `tox` because is faster. 
- Configures Coverage Threshold for failure at [coveralls.io](https://coveralls.io/github/HewlettPackard/py-spiffe) site. Test coverage now is 91.4%. New builds will fail if test coverage is less than 90%.
Note: In order to post coverage reports to `coveralls.io`, we need to set the Env Var `COVERALLS_REPO_TOKEN` on CircleCi (is set as project level). …

Adds lint and test coverage report jobs to CI

---

src/pyspiffe/bundle/x509_bundle/x509_bundle.py
src/pyspiffe/bundle/x509_bundle/x509_bundle_set.py
src/pyspiffe/svid/x509_svid.py
test/bundle/x509bundle/test_x509_bundle.py
test/bundle/x509bundle/test_x509_bundle_set.py
test/svid/x509svid/test_x509_svid.py

This PR makes the types `X509Svid`, `X509Bundle`, and `X509BundleSet` immutable and thread-safe by making the getters returns copies of the internal collections, making the constructors deepcopy the collections passed as arguments, and making the `add` and `remove` methods use a Lock to prevent data-races.
Once this PR gets the approval of the team, there will remain to make the same kind of adaptations to the other types (`JWTBundle`, etc)

Enforce immutability and thread-safety on X.509 SVIDs and Bundle objects

---

src/pyspiffe/workloadapi/default_workload_api_client.py

A couple methods on the `DefaultWorkloadApiClient` take parameters types as `Any`. This PR improves it by using more specific types, and adds the return type on one method that is missing it. 

Improve typing on some methods of the DefaultWorkloadApiClient

---

src/pyspiffe/svid/jwt_svid.py
src/pyspiffe/svid/jwt_svid_validator.py
src/pyspiffe/workloadapi/default_workload_api_client.py
src/pyspiffe/workloadapi/exceptions.py
test/svid/jwtsvid/test_jwt_svid.py
test/svid/jwtsvid/test_jwt_svid_validator.py
test/svid/test_utils.py
test/workloadapi/test_default_workload_api_client.py
test/workloadapi/test_default_workload_api_client_fetch_x509.py
test/workloadapi/test_default_workload_api_client_jwt.py

This PR also updates the code to use a set instead of a list as parameters when calling `JwtSvid()`, `JwtSvid.parse_insecure()` and `JwtSvid.pase_and_validate()`. This where required based on a previous update.

Implements ValidateJWTSVID(). 

---

src/pyspiffe/bundle/jwt_bundle/exceptions.py
src/pyspiffe/bundle/jwt_bundle/jwt_bundle.py
src/pyspiffe/bundle/x509_bundle/exceptions.py
src/pyspiffe/bundle/x509_bundle/x509_bundle.py
src/pyspiffe/config.py
src/pyspiffe/exceptions.py
src/pyspiffe/spiffe_id/spiffe_id.py
src/pyspiffe/spiffe_id/trust_domain.py
src/pyspiffe/svid/__init__.py
src/pyspiffe/svid/exceptions.py
src/pyspiffe/svid/jwt_svid.py
src/pyspiffe/svid/jwt_svid_validator.py
src/pyspiffe/svid/x509_svid.py
src/pyspiffe/utils/exceptions.py
src/pyspiffe/workloadapi/default_workload_api_client.py
src/pyspiffe/workloadapi/exceptions.py
test/bundle/jwt_bundle/test_jwt_bundle.py
test/bundle/x509bundle/test_x509_bundle.py
test/spiffe_id/test_spiffe_id.py
test/spiffe_id/test_trust_domain.py
test/svid/jwtsvid/test_jwt_svid.py
test/svid/jwtsvid/test_jwt_svid_validator.py
test/svid/x509svid/test_x509_svid.py
test/test_config.py
test/utils/test_certificate_utils.py
test/workloadapi/test_default_workload_api_client.py
test/workloadapi/test_default_workload_api_client_jwt.py

This PR updates the errors thrown by the library to include a dot at the end of the message automatically.
The changes:
* All custom exceptions inherit from `PySpiffeError`, the top level exception for the library.
* The final dot in the message is not necessary when raising an exception.
* To be consistent in the code, the new exception `ArgumentError` is created to replace all occurrences of `ValueError`.
This way, all error messages in the code looks the same and there is no need for a final dot. I removed the final dot from all places to make things clearer.

All exception messages end up with a dot automatically.

---

Pipfile
Pipfile.lock
src/pyspiffe/bundle/jwt_bundle/exceptions.py
src/pyspiffe/bundle/jwt_bundle/jwt_bundle.py
src/pyspiffe/bundle/x509_bundle/exceptions.py
src/pyspiffe/bundle/x509_bundle/x509_bundle.py
src/pyspiffe/svid/exceptions.py
src/pyspiffe/utils/exceptions.py
src/pyspiffe/workloadapi/exceptions.py

As noted recently by a failing build on CircleCI, there is a new version of `black` released today.
The new version (in between some [other changes](https://github.com/psf/black/blob/master/CHANGES.md#214b0)) is reporting white spaces at the end of one line docstrings as errors. Our code have a some occurrences of this pattern and that is making the link task fail.
This PR updates `black` to the latest version and also fixes all the occurrences of the mentioned error. This keep in sync the version used locally with the one used when running con CircleCI.

Updates Black to latest version

---

src/pyspiffe/bundle/x509_bundle/x509_bundle.py
src/pyspiffe/svid/x509_svid.py
test/bundle/x509bundle/test_x509_bundle.py
test/svid/x509svid/test_x509_svid.py

Refactor the `save` methods in `X509Svid` and `X509Bundle` to be an instance methods, which makes a lot more sense than having a static method to be called through the class. So now the call to save an `X509Svid` would look like:
`my_svid.save('/tmp/my_cert.pem', /tmp/my_key.pem', encoding.PEM)`

Refactor 'save's as instance methods.

---

src/pyspiffe/spiffe_id/trust_domain.py
test/spiffe_id/test_trust_domain.py

The parse TrustDomain method is currently allowing parsing strings that include userinfo (e.g. `user:pass@domain.test`). Added a validation to prevent that.

Add missing validation in TrustDomain

---

src/pyspiffe/workloadapi/default_workload_api_client.py
src/pyspiffe/workloadapi/default_x509_source.py
src/pyspiffe/workloadapi/exceptions.py
src/pyspiffe/workloadapi/workload_api_client.py
src/pyspiffe/workloadapi/x509_context.py
src/pyspiffe/workloadapi/x509_source.py
test/workloadapi/test_default_workload_api_client_fetch_x509.py
test/workloadapi/test_x509_context.py
test/workloadapi/test_x509_source.py

This is the implementation of an X.509 Source that is kept updated by an underlying Workload API client connection that retrieves the X.509 context updates.
As part of this implementation some minor changes were made on the Workload API client with respect to the report of the error to the clients on the `watch_x509_context` method. Also some validations were added on the constructor of the X509Context.
Solves #69 

Implement X.509 Source

---

src/pyspiffe/workloadapi/default_workload_api_client.py
src/pyspiffe/workloadapi/handle_error.py
test/workloadapi/test_default_workload_api_client_fetch_x509.py
test/workloadapi/test_default_workload_api_client_jwt.py
test/workloadapi/test_handle_error.py

This PRs unified the error handling on the `default_workload_api_client.py`.
This includes checking if the error response is a `grpc.Call` which contains an error Code and Details. If it is the case, the details are included in the exception thrown to the user of the library.

Unify error handling on default workload API

---

src/pyspiffe/__init__.py
src/pyspiffe/workloadapi/default_workload_api_client.py
src/pyspiffe/workloadapi/default_x509_source.py

The configuration creates a new logger for the library with a `NullHandler` to avoid any message to be logged.
This allows the library to be integrated with the library's client logging configuration.
If required, a client of the library can set the log level by:
```
py_spiffe_logger = logging.getLogger('pyspiffe')
py_spiffe_logger.setLevel(logging.DEBUG)
``` 
On the other hand, inside the library we create a logger per module using:
`_logger = logging.getLogger(__name__)`
This allows us to get a logger with a name that follows the library architecture. For example, when getting a logger at `default_workload_api_client.py` we end up having a log record from a logger called `pyspiffe.workloadapi.default_workload_api_client`.
Solves https://github.com/HewlettPackard/py-spiffe/issues/95

Adds logging configuration

---

spiffe/src/spiffe/workloadapi/workload_api_client.py

Adjusting  Retry Max Delay default value to 5 seconds.
Given the context of the Workload API listening on a local socket and likely serving a limited number of workloads, adjusting the Retry Max Delay default value to a more reasonable value, such as 5 seconds, can enhance efficiency and responsiveness. This adjustment acknowledges the balance between providing timely updates and not overly taxing the system resources or flooding the Workload API with requests during periods of rapid changes or temporary issues.

Adjusting  Retry Max Delay default value to 5 seconds.

---

.github/workflows/publish.yaml

This PR introduces a GitHub Actions workflow for automated publishing of the spiffe and spiffe-tls Python modules to PyPI. It triggers on tags `spiffe-*` and `spiffe-tls-*`, using conditional logic to publish the relevant module based on the tag. The workflow employs Poetry for packaging and leverages GitHub Secrets for secure PyPI authentication.
Features:
- Tag-based Triggers: Initiates publishing based on spiffe-* or spiffe-tls-* tags.
- Conditional Publishing: Determines which module to publish based on the tag prefix.
- Secure & Automated: Uses stored PyPI credentials for secure, automated publishing.

Automate PyPI Publishing with GitHub Actions

---

spiffe/src/spiffe/bundle/jwt_bundle/jwt_bundle.py
spiffe/tests/unit/bundle/jwt_bundle/test_jwt_bundle.py

This PR improves the handling of JSON Web Key Sets (JWKS) for cases where the JWKS document has an empty keys array or a null keys value. 

Handle JWKS With Empty And Null Values
